#!/bin/bash

set -e

# Build
arduino-cli compile \
    --fqbn STMicroelectronics:stm32:GenF1:pnum=BLACKPILL_F103CB,upload_method=dfu2Method,xserial=generic,usb=none \
    --verbose \
    --export-binaries . > build.log

# Flash
dfu-util -d 1eaf:0003 -a 2 -D build/STMicroelectronics.stm32.GenF1/firmware.ino.bin

